[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[server]
enableCORS = false
enableXsrfProtection = false

[deprecation]
showPyplotGlobalUse = false
showfileUploaderEncoding = false

[logger]
level = "error"